spring:
  datasource:
    url: jdbc:postgresql://db.geoiyrmlwkrbdzsjsvvi.supabase.co:5432/postgres
    username: postgres
    password: Neym@r10gt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level: